### ISSUE TITLE
Documentation recommendation

### ISSUE THREAD

**Issue by t3nsed** [patrick-11/FlashyFlashCards#1]
The installation and running part is kind of unintuitive in my opinion, since it already assumes the user has `npm` installed and cloned the repo. Furthermore, the `cd` statement assumes the user is in the project root, which is not the case after `git clone`.

![...](https://i.kym-cdn.com/entries/icons/original/000/021/665/DpQ9YJl.png "MUH DOCS")

**Comment by patrick-11** [comment]
ACKCHYUALLY
